# Generated by Django 5.0.6 on 2024-07-22 20:59

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=500)),
                ('country', models.CharField(default='Canada', max_length=300)),
                ('province', models.CharField(default='ON', max_length=10)),
                ('city', models.CharField(default='Windsor', max_length=500)),
                ('mobileNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ManyToManyField(related_name='category', to='PetForum.category')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetForum.member')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer', models.TextField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetForum.member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetForum.question')),
            ],
        ),
    ]
