# Generated by Django 5.0.6 on 2024-06-12 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PetForum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="creationDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 12, 0, 18, 52, 275915, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="updationDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 12, 0, 18, 52, 275926, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="creationDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 12, 0, 18, 52, 275155, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="updationDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 12, 0, 18, 52, 275335, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
