# Generated by Django 4.2.11 on 2024-06-12 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetForum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 7, 17, 7, 854491, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 7, 17, 7, 854501, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 7, 17, 7, 853453, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='updationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 7, 17, 7, 853681, tzinfo=datetime.timezone.utc)),
        ),
    ]
