# Generated by Django 4.2.11 on 2024-06-12 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetForum', '0002_alter_answer_creationdate_alter_answer_updationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 7, 45, 53, 476055, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 7, 45, 53, 476066, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 7, 45, 53, 475041, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='updationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 7, 45, 53, 475268, tzinfo=datetime.timezone.utc)),
        ),
    ]
