# Generated by Django 5.0.6 on 2024-06-19 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetForum', '0004_alter_answer_creationdate_alter_answer_updationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 7, 11, 51, 644251, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 7, 11, 51, 644251, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 7, 11, 51, 644251, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='updationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 7, 11, 51, 644251, tzinfo=datetime.timezone.utc)),
        ),
    ]
