# Generated by Django 5.0.6 on 2024-06-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetForum', '0006_alter_answer_creationdate_alter_answer_updationdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='cat_title',
        ),
    ]
