# Generated by Django 5.0.7 on 2024-07-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetForum', '0006_alter_answer_creationdate_alter_answer_updationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobileNo',
            field=models.IntegerField(),
        ),
    ]
