# Generated by Django 5.0.6 on 2024-06-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetForum', '0007_rename_title_category_cat_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_title',
            new_name='title',
        ),
    ]
