# Generated by Django 5.0.6 on 2024-06-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetForum', '0009_alter_category_description_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
