# Generated by Django 5.0.6 on 2024-06-30 01:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetForum', '0011_remove_question_category_remove_question_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ManyToManyField(related_name='category', to='PetForum.category')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetForum.member')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer', models.TextField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetForum.member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetForum.question')),
            ],
        ),
    ]
