# Generated by Django 5.0.6 on 2024-07-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetForum', '0014_alter_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
