# Generated by Django 5.0.6 on 2024-07-24 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PetForum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='img/image1.jpg', upload_to='img/')),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('species', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetForum.member')),
            ],
        ),
    ]
