# Generated by Django 4.2.11 on 2024-07-24 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='img/image1.jpg', upload_to='img/')),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('species', models.TextField()),
            ],
        ),
    ]
