<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-06-23 04:06

=======
<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-06-28 20:32

=======
# Generated by Django 5.0.6 on 2024-06-25 21:36

import django.db.models.deletion
import django.utils.timezone
>>>>>>> d000236b52ba6c002dbc93c794c8f50e1e94a699
>>>>>>> 483db394b11eb08820a37dd552a81764791c90ff
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
        ('PetForum', '0006_alter_answer_creationdate_alter_answer_updationdate_and_more'),
>>>>>>> d000236b52ba6c002dbc93c794c8f50e1e94a699
>>>>>>> 483db394b11eb08820a37dd552a81764791c90ff
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('species', models.TextField()),
=======
<<<<<<< HEAD
                ('species', models.TextField()),
=======
                ('image', models.ImageField(upload_to='img/')),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('species', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetForum.member')),
>>>>>>> d000236b52ba6c002dbc93c794c8f50e1e94a699
>>>>>>> 483db394b11eb08820a37dd552a81764791c90ff
            ],
        ),
    ]
