# Generated by Django 4.2.11 on 2024-07-24 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adoption', '0001_initial'),
        ('PetForum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetForum.member'),
        ),
    ]
