# Generated by Django 5.0.6 on 2024-07-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='image',
            field=models.ImageField(default='img/image1.jpg', upload_to='img/'),
        ),
    ]
