# Generated by Django 5.0.6 on 2024-07-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption', '0002_alter_adoption_image'),
        ('Adoption', '0002_initial'),
    ]

    operations = [
    ]
